services:
  data-reciever:
    build: docker/data-reciever
    volumes:
      - ./src/data-reciever:/var/www/html
    ports:
      - 80:80
    expose:
      - 9003
    depends_on:
      database:
        condition: service_healthy
  database:
    build: docker/database
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: weather
    volumes:
      - ./src/database/scripts/:/docker-entrypoint-initdb.d/
    ports:
      - 3306:3306
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 15s
      timeout: 20s
      retries: 10
  data-visualisation:
    build: docker/data-visualisation
    ports:
      - 3000:3000
    depends_on:
      database:
        condition: service_healthy
    volumes:
      - grafana-storage:/var/lib/grafana
volumes:
  grafana-storage: