services:
  app:
    build: docker/app
    volumes:
      - ./app:/var/www/html
      - ./db-config.php:/var/www/db-config.php
    ports:
      - 80:80
    expose:
     - 9003
    depends_on:
      database:
        condition: service_healthy
  database:
    build: .
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: weather
    volumes:
      - ./database/:/docker-entrypoint-initdb.d/
    ports:
      - 3306:3306
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      interval: 10s
      timeout: 20s
      retries: 10
  data-visualisation:
    image: grafana/grafana:latest
    ports:
      - 3000:3000
    depends_on:
      database:
        condition: service_healthy