-- MySQL Script generated by MySQL Workbench
-- Sat Nov 11 19:51:57 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema weather
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema weather
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `weather` DEFAULT CHARACTER SET utf8 ;
USE `weather` ;

-- -----------------------------------------------------
-- Table `weather`.`sensors`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `weather`.`sensors` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `weather`.`data`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `weather`.`data` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `value` INT NOT NULL,
  `sensors_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `FK_sens_dat_idx` (`sensors_id` ASC) VISIBLE,
  CONSTRAINT `FK_sens_dat`
    FOREIGN KEY (`sensors_id`)
    REFERENCES `weather`.`sensors` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
